config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :permissions
  resources :roles
  resources :users
  get 'oo_admin/index'
  
  get 'oo_admin/login'

  get 'welcome/index'

   root 'welcome#index'

end

app/models/permission.rb
class Permission
  include Mongoid::Document
  include Mongoid::Timestamps

  field :controller, type: String
  field :action, type: String

  has_and_belongs_to_many :roles
end

app/controllers/permissions_controller.rb
class PermissionsController < ApplicationController
  before_action :set_permission, only: [:show, :edit, :update, :destroy]
  layout 'managementSystem'

  # GET /permissions
  # GET /permissions.json
  def index
    @permissions = Permission.all
  end

  # GET /permissions/1
  # GET /permissions/1.json
  def show
  end

  # GET /permissions/new
  def new
    @permission = Permission.new
  end

  # GET /permissions/1/edit
  def edit
  end

  # POST /permissions
  # POST /permissions.json
  def create
    @permission = Permission.new(permission_params)

    respond_to do |format|
      if @permission.save
        format.html { redirect_to @permission, notice: 'Permission was successfully created.' }
        format.json { render :show, status: :created, location: @permission }
      else
        format.html { render :new }
        format.json { render json: @permission.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /permissions/1
  # PATCH/PUT /permissions/1.json
  def update
    respond_to do |format|
      if @permission.update(permission_params)
        format.html { redirect_to @permission, notice: 'Permission was successfully updated.' }
        format.json { render :show, status: :ok, location: @permission }
      else
        format.html { render :edit }
        format.json { render json: @permission.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /permissions/1
  # DELETE /permissions/1.json
  def destroy
    @permission.destroy
    respond_to do |format|
      format.html { redirect_to permissions_url, notice: 'Permission was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_permission
      @permission = Permission.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def permission_params
      params.require(:permission).permit(:namespace, :controller, :action)
    end
end

app/helpers/permissions_helper.rb
module PermissionsHelper
end

app/views/permissions/_form.html.erb
<%= form_for @permission, :html => { :class => "form-horizontal permission" } do |f| %>

  <% if @permission.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@permission.errors.count, "error") %> prohibited this permission from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @permission.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :namespace, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :namespace, :class => 'form-control' %>
    </div>
    <%=f.error_span(:namespace) %>
  </div>
  <div class="form-group">
    <%= f.label :controller, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :controller, :class => 'form-control' %>
    </div>
    <%=f.error_span(:controller) %>
  </div>
  <div class="form-group">
    <%= f.label :action, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :action, :class => 'form-control' %>
    </div>
    <%=f.error_span(:action) %>
  </div>
  <div class="form-group">
    <%= f.label :role_ids, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :role_ids, :class => 'form-control' %>
    </div>
    <%=f.error_span(:role_ids) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                permissions_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/permissions/edit.html.erb
<%- model_class = Permission -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/permissions/index.html.erb
<%- model_class = Permission -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:namespace) %></th>
      <th><%= model_class.human_attribute_name(:controller) %></th>
      <th><%= model_class.human_attribute_name(:action) %></th>
      <th><%= model_class.human_attribute_name(:role_ids) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @permissions.each do |permission| %>
      <tr>
        <td><%= link_to permission.id, permission_path(permission) %></td>
        <td><%= permission.namespace %></td>
        <td><%= permission.controller %></td>
        <td><%= permission.action %></td>
        <td><%= permission.role_ids %></td>
        <td><%=l permission.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_permission_path(permission), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      permission_path(permission),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_permission_path,
            :class => 'btn btn-primary' %>

app/views/permissions/new.html.erb
<%- model_class = Permission -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/permissions/show.html.erb
<%- model_class = Permission -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:namespace) %>:</strong></dt>
  <dd><%= @permission.namespace %></dd>
  <dt><strong><%= model_class.human_attribute_name(:controller) %>:</strong></dt>
  <dd><%= @permission.controller %></dd>
  <dt><strong><%= model_class.human_attribute_name(:action) %>:</strong></dt>
  <dd><%= @permission.action %></dd>
  <dt><strong><%= model_class.human_attribute_name(:role_ids) %>:</strong></dt>
  <dd><%= @permission.role_ids %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              permissions_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_permission_path(@permission), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              permission_path(@permission),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>