config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :permissions
  resources :roles
  resources :users
  get 'oo_admin/index'
  
  get 'oo_admin/login'

  get 'welcome/index'

   root 'welcome#index'

end

app/models/role.rb
class Role
  include Mongoid::Document
  include Mongoid::Timestamps

  field :name, type: String
  field :desc, type: String

  has_and_belongs_to_many :users
  has_and_belongs_to_many :permissions
end

app/controllers/roles_controller.rb
class RolesController < ApplicationController
  before_action :set_role, only: [:show, :edit, :update, :destroy]
  layout 'managementSystem'
  # GET /roles
  # GET /roles.json
  def index
    @roles = Role.all
  end

  # GET /roles/1
  # GET /roles/1.json
  def show
  end

  # GET /roles/new
  def new
    @role = Role.new
  end

  # GET /roles/1/edit
  def edit
  end

  # POST /roles
  # POST /roles.json
  def create
    @role = Role.new(role_params)

    respond_to do |format|
      if @role.save
        format.html { redirect_to @role, notice: 'Role was successfully created.' }
        format.json { render :show, status: :created, location: @role }
      else
        format.html { render :new }
        format.json { render json: @role.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /roles/1
  # PATCH/PUT /roles/1.json
  def update
    respond_to do |format|
      if @role.update(role_params)
        format.html { redirect_to @role, notice: 'Role was successfully updated.' }
        format.json { render :show, status: :ok, location: @role }
      else
        format.html { render :edit }
        format.json { render json: @role.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /roles/1
  # DELETE /roles/1.json
  def destroy
    @role.destroy
    respond_to do |format|
      format.html { redirect_to roles_url, notice: 'Role was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_role
      @role = Role.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def role_params
      params.require(:role).permit(:name, :desc, :permission_ids)
    end
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/views/roles/_form.html.erb
<%= form_for @role, :html => { :class => "form-horizontal role" } do |f| %>

  <% if @role.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@role.errors.count, "error") %> prohibited this role from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @role.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :name, :class => 'form-control' %>
    </div>
    <%=f.error_span(:name) %>
  </div>
  <div class="form-group">
    <%= f.label :desc, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :desc, :class => 'form-control' %>
    </div>
    <%=f.error_span(:desc) %>
  </div>
  <div class="form-group">
    <%= f.label :permissions, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :permissions, :class => 'form-control' %>
    </div>
    <%=f.error_span(:permissions) %>
  </div>
  <div class="form-group">
    <%= f.label :user_ids, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :user_ids, :class => 'form-control' %>
    </div>
    <%=f.error_span(:user_ids) %>
  </div>
  <div class="form-group">
    <%= f.label :permission_ids, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :permission_ids, :class => 'form-control' %>
    </div>
    <%=f.error_span(:permission_ids) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit t('.create', :default => t("helpers.links.create")), :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                roles_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/roles/edit.html.erb
<%- model_class = Role -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/roles/index.html.erb
<%- model_class = Role -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:desc) %></th>
      <th><%= model_class.human_attribute_name(:permissions) %></th>
      <th><%= model_class.human_attribute_name(:user_ids) %></th>
      <th><%= model_class.human_attribute_name(:permission_ids) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @roles.each do |role| %>
      <tr>
        <td><%= link_to role.id, role_path(role) %></td>
        <td><%= role.name %></td>
        <td><%= role.desc %></td>
        <td><%= role.permissions %></td>
        <td><%= role.user_ids %></td>
        <td><%= role.permission_ids %></td>
        <td><%=l role.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_role_path(role), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      role_path(role),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_role_path,
            :class => 'btn btn-primary' %>

app/views/roles/new.html.erb
<%- model_class = Role -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/roles/show.html.erb
<%- model_class = Role -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @role.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:desc) %>:</strong></dt>
  <dd><%= @role.desc %></dd>
  <dt><strong><%= model_class.human_attribute_name(:permissions) %>:</strong></dt>
  <dd><%= @role.permissions %></dd>
  <dt><strong><%= model_class.human_attribute_name(:user_ids) %>:</strong></dt>
  <dd><%= @role.user_ids %></dd>
  <dt><strong><%= model_class.human_attribute_name(:permission_ids) %>:</strong></dt>
  <dd><%= @role.permission_ids %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              roles_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_role_path(@role), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              role_path(@role),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>